import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/shared/tanstack-query/Provider";
import Header from "@/shared/components/header/Header";
import Footer from "@/shared/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
        {/* <ToastProvider /> */}
      </body>
    </html>
  );
}
